- name: Testing purpose
  hosts: proxy
  become: true
  tasks:
    - name: Get device /dev/vdb available storage
      community.general.parted:
        device: /dev/vdb
        unit: MiB
      register: dev_vdb



    - name: Debug message
      ansible.builtin.debug:
        msg: "{{ dev_vdb }}"

    - name: Debug message
      ansible.builtin.debug:
        msg: >-
          {% if dev_vdb.disk.size > 1500 %}
          /dev/vdb is more than 1500
          {% elif dev_vdb.disk.size > 800 %}
          /dev/vdb is more than 800
          {% endif %}

    - name: Create 1500MiB storage logical vol group
      ansible.builtin.include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: vg0
            disks:
              - /dev/vdb
            volumes:
              - name: lv0
                fs_type: xfs
                state: absent
                size: >-
                  {% if dev_vdb.disk.size > 1500 %}
                  1500m
                  {% elif dev_vdb.disk.size > 800 %}
                  800m
                  {% endif %}

