- name: gather facts 
  hosts: all

- name: gather_facts
  hosts: localhost
  tasks:
    - name: template
      ansible.builtin.debug:
        msg: "{{ hostvars[item].ansible_facts['hostname'] }} {{ idx }}"
      with_items: "{{ groups.serversitus }}"
      loop_control:
        index_var: idx

#     ansible.builtin.set_fact:
#       backend_servers: "{{ backend_servers|default([]) + [ 
