- name: Generate /etc/issue
  hosts: all

  tasks:
    - name: Generate /etc/issue
      ansible.builtin.copy:
        dest: /etc/issue
        content: "{{ issue_message }} \n"
        owner: root
        group: root
        mode: 0644
      when: issue_message is defined
