- name: Configure haproxy
  hosts: proxy
  become: true
  tasks:
    - name: set facts 
      ansible.builtin.set_fact:
        haproxy_servers: "{{ haproxy_servers|default([]) + [ {'name': 'app-'+idx|string, 'address':  item } ] }}"
      with_items: "{{ groups.serversitus }}"
      loop_control:
        index_var: idx

    - name: debug msg
      ansible.builtin.debug:
        msg: "{{ haproxy_servers }}"

    - name: import role
      ansible.builtin.include_role:
        name: geerlingguy.haproxy
      vars:
        haproxy_backend_servers: "{{ haproxy_servers }}"
