- name: Configure logical volume for remote servers
  hosts: all
  become: true
  roles:
    - name: redhat.rhel_system_roles.storage
      storage_pools:
        - name: vg0
          disks:
            - /dev/vdb
          volumes:
            - name: lv0
              size: 800MiB
              fs_type: xfs
              state: present
