- name: Add hosts file to remote hosts
  hosts: all
  become: true
  tasks:
    - name: Add hosts file to /root/myhosts
      ansible.builtin.template:
        src: hosts.j2
        dest: /root/myhosts
        owner: root
        group: root

