- name: Testing
  hosts: all
  become: true
  tasks:
    - name: inventory_hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: groups
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: group_names
      ansible.builtin.debug:
        msg: "{{ group_names }}"
