- name: Use myvhost role playbook
  hosts: webservers
  pre_tasks:
    - name: pre-tasks message
      ansible.builtin.debug:
        msg: 'Ensure  web server configuration'

  roles:
    - myvhost

  post_tasks:
    - name: HTML content is installed
      ansible.builtin.copy:
        src: files/html/
        dest: "/var/www/vhosts/{{ ansible_hostname }}"

    - name: post_tasks mesage
      ansible.builtin.debug:
        msg: 'web server is configured'

