---
# tasks file for sample-apache
#
- name: Start httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: start firewall
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: start firewall
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled

- name: Copy templates to remote host
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
