- name: Task Failure Exercises
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Check local time
      ansible.builtin.command: date
      register: command_result
      # ansible.builtin.command tidak tahu apakah command nya
      # akan mengubah sesuatu atau tidak sehingga akan selalu mengeluarkan status 'changed'
      # dengan changed_when: false maka akan mengubah status menjadi 'ok'
      changed_when: false

    - name: Print local time
      ansible.builtin.debug:
        var: command_result.stdout

    - name: Attempt to start a webserver
      # Equivalent to try in python
      block:
        - name: Install {{ web_package }} package
          ansible.builtin.dnf:
            name: "{{ web_package }}"
            state: present
          # failed_when akan failed apabila web_package == "httpd"
          failed_when: web_package == "httpd"

      # Equivalent to except in python
      rescue:
        - name: Install {{ db_package }} package
          ansible.builtin.dnf:
            name: "{{ db_package }}"
            state: present

      # Equivalent to finally in python
      always:
        - name: Start {{ db_service }} service
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started
